version: '3.9'

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    # Charge la config statique depuis le fichier monté
    command: ['--configFile=~/yabara/traefik/traefik.yml']
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:~/yabara/traefik/traefik.yml:ro
      - ./traefik/dynamic:/dynamic:ro
      - ./traefik/letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      # Dashboard Traefik
      - traefik.http.routers.traefik.rule=Host(`traefik.yabara.co`)
      - traefik.http.routers.traefik.entrypoints=web,websecure
      - traefik.http.routers.traefik.middlewares=redirect-to-https@file
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.service=api@internal
    restart: unless-stopped
    networks: [traefik]

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`yabara.co`)
      - traefik.http.routers.client.entrypoints=web,websecure
      - traefik.http.routers.client.middlewares=redirect-to-https@file
      - traefik.http.routers.client.tls.certresolver=le
      - traefik.http.services.client.loadbalancer.server.port=80
    depends_on: [server]
    restart: unless-stopped
    networks: [traefik, internal]

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`api.yabara.co`)
      - traefik.http.routers.server.entrypoints=web,websecure
      - traefik.http.routers.server.middlewares=redirect-to-https@file
      - traefik.http.routers.server.tls.certresolver=le
      - traefik.http.services.server.loadbalancer.server.port=3310
    depends_on: [mysql]
    restart: unless-stopped
    networks: [traefik, internal]

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: unless-stopped
    networks: [internal]

volumes:
  mysql_data:

networks:
  traefik:
  internal:
    driver: bridge
