#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Vérifie que certains fichiers ne sont pas modifiés
fileList=$(git diff --staged --name-only :^package-lock.json :^README.md :^client :^server)

echo '----- Checking Root...'

if [ ! -z "$fileList" ]
then
  echo "error: Unauthorized modifications\n"
  echo "$fileList\n"
  echo "use 'git restore --staged ...' to fix the problem"
  exit 1
fi

echo '----- Done!'

# Lance lint-staged pour formater automatiquement les fichiers modifiés
npx lint-staged
