name: 🚀 Deploy Yabara

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            echo "➡️ Passage dans le dossier du projet"
            cd ~/yabara

            echo "➡️ Pull des dernières modifs"
            git fetch origin main
            git reset --hard origin/main

            echo "➡️ Redémarrage des conteneurs"
            docker compose down
            docker compose up -d --build --remove-orphans

            echo "✅ Déploiement terminé !"
